name: Validation des Structures de Donnees

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-structures:
    runs-on: ubuntu-latest

    steps:
    - name: Recuperer le code du depot
      uses: actions/checkout@v4

    - name: Configurer Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Configurer Java (JDK 17)
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    
    - name: Executer les tests HashMap
      run: |
        python 09_HashMap/python/hashmap.py
        gcc 09_HashMap/c/hashmap.c -o hashmap_test && ./hashmap_test

    - name: Executer les tests Stack
      run: |
        python 05_Stack/python/stack.py
        gcc 05_Stack/c/stack.c -o stack_test && ./stack_test

    
    - name: Executer le test Python Linked List
      run: python 07_LinkedList/python/linked_list.py

    - name: Compiler et Executer C Linked List
      run: gcc 07_LinkedList/c/linked_list.c -o ll_c && ./ll_c

    - name: Compiler et Executer Java Linked List
      run: |
        javac 07_LinkedList/java/LinkedListTest.java
        java -ea -cp 07_LinkedList/java LinkedListTest

