name: Validation des Structures de Donnees

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-structures:
    runs-on: ubuntu-latest

    steps:
    - name: Recuperer le code du depot
      uses: actions/checkout@v4

    - name: Configurer Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Configurer Java (JDK 17)
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    # Le Makefile s'occupe de tout en une seule ligne !
    - name: Executer l'ensemble des tests via le Makefile
      run: make test

